### ISSUE TITLE
The Kernel Gateway shutdown automatically

### ISSUE THREAD

**Issue by khacminh** [aws/studio-lab-examples#103]
**Describe the bug**

Hello, 

I chose datascience-1-0-ml-c5-2xlarge to run my notebook. Sometimes, the kernel gateway app shut down automatically and is then Deleted. This issue doesn't occur while doing the lab. It occurs sometimes when I use sagemaker studio for my project. Does anyone know what makes the root cause and how to fix it?

**Screenshots**

![Screen Shot 2022-04-19 at 09 47 14](https://user-images.githubusercontent.com/13713865/163920587-796f1d29-cabb-4511-bf02-61bec0b53410.png)

**Additional context**

Checking the cloudwatch log, I see the following error:

```txt
[E yyMMdd hh:mm:ss web:1219] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 239, in get
        yield super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/base/zmqhandlers.py", line 291, in get
        yield maybe_future(res)
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 221, in pre_get
        kernel = self.kernel_manager.get_kernel(self.kernel_id)
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 318, in get_kernel
        self._check_kernel_id(kernel_id)
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 387, in _check_kernel_id
        raise web.HTTPError(404, u'Kernel does not exist: %s' % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 7a87cd59-af9c-476e-894b-dc615b275dfd)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/tornado/web.py", line 1217, in send_error
        self.write_error(status_code, **kwargs)
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/base/handlers.py", line 576, in write_error
        html = self.render_template('%s.html' % status_code, **ns)
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/base/handlers.py", line 506, in render_template
        template = self.get_template(name)
      File "/opt/.sagemakerinternal/conda/lib/python3.7/site-packages/notebook/base/handlers.py", line 502, in get_template
        return self.settings['jinja2_env'].get_template(name)
    KeyError: 'jinja2_env'
```

Thank you in advance.

**Comment by icoxfog417** [comment]
@khacminh Thank you for your report. Your environment seems to be SageMaker Studio. Here is SageMaker Studio Lab, it is different service for each other.

**Comment by khacminh** [comment]
Hi,

I can fix the issue now.

Thank you
