### ISSUE TITLE
!nvidia-smi shows CUDA 12.2, but !nvcc -V shows 11.2 CUDA Compiler version

### ISSUE THREAD

**Issue by Rorutop** [aws/studio-lab-examples#250]
I was trying to install flash-attn for ComfyUI-ExLlama-Nodes, but i was greeted with this error:
```
    ERROR: Command errored out with exit status 1:
     command: /home/studio-lab-user/.conda/envs/default/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jlkcxk9h/flash-attn_abe85aae80da4140845572141db7a95a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jlkcxk9h/flash-attn_abe85aae80da4140845572141db7a95a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uyl4bktx
         cwd: /tmp/pip-install-jlkcxk9h/flash-attn_abe85aae80da4140845572141db7a95a/
    Complete output (11 lines):
    fatal: not a git repository (or any of the parent directories): .git
    
    
    torch.__version__  = 2.1.0+cu118
    
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jlkcxk9h/flash-attn_abe85aae80da4140845572141db7a95a/setup.py", line 114, in <module>
        raise RuntimeError(
    RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.
```

It told me to use `nvcc -V`, so i tried to execute it and gave me this
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```
I thought to check nvdia-smi, got me CUDA 12.2
```
Mon Feb 26 09:42:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:1E.0 Off |                    0 |
| N/A   27C    P0              25W /  70W |      2MiB / 15360MiB |      5%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

So i wonder if this is a mistake on putting the CUDA compiler as 11.2, not 12.2?

**Comment by MicheleMonclova** [comment]
Are yo sure this is a bug? Did you check out the advice on this blog? https://komodor.com/blog/solving-fatal-not-a-git-repository-error/

**Comment by Rorutop** [comment]
> Are yo sure this is a bug? Did you check out the advice on this blog? https://komodor.com/blog/solving-fatal-not-a-git-repository-error/

Im referring to the `RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.`, not a git repository error.

That's why im asking if this is a mistake setting the CUDA compiler as 11.2 instead of 12.2. Checking on google colab its compiler is at 12.2 with !nvcc -V, but not sagemaker studio lab.

**Comment by Rorutop** [comment]
Well tbh I expected someone that was responsible for making the runtime stuff on the Sagemaker Studio Lab looked into this... They should be able to update CUDA Compiler to 12.2 though
